---
- name: Criando um usuário e grupo
  hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
    - name: Verfica se o grupo devops existe
      group:
        name: devops
        state: present

    - name: Criando o usuário
      user:
        name: csp_jenkins
        comment: Usuario administrativo para o Jenkins
        uid: 1040
        group: devops

