---
- name: Upload Config File
  hosts: lab
  become: yes
  gather_facts: yes
  vars:
    file_src: config.json
    file_dest: /usr/src
    owner: root
    group: root
    mode: 0777
  tasks:
    - name: Upload file
      template:
        src:  "{{file_src}}"
        dest: "{{file_dest}}"
        owner: "{{owner}}"
        group: "{{group}}"
        mode: "{{mode}}"
      register: upload_file
    - name: Altera o ambiente para apontar para producao
      replace:
        backup: true
        path: '{{file_dest}}//{{file_src}}'
        regexp: "development"
        replace: "production"
      when: upload_file is success
